"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["ScreenCapX.py"]
DATA_FILES = []
OPTIONS = {
    "argv_emulation": False,
    "packages": ["rumps", "PIL", "Quartz", "pynput"],  # Include all required packages
    "excludes": ["packaging"],
    "plist": {
        "NSHighResolutionCapable": True,
        "NSPrincipalClass": "NSApplication",
        "CFBundleName": "ScreenCapX",  # Your app's name
        "CFBundleIdentifier": "com.ekinertac.ScreenCapX",  # Change to your unique identifier
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
